/*#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorNone)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          rightsweeper,  tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          leftsweeper,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightmotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftmotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     blockgrabber,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     robotlifter,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     flagraiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     throwerMotor,  tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
/!!Code automatically generated by 'ROBOTC' configuration wizard               !!/

//As a Driver I want to flip blocks into bucket and want it to stop at a certain distance.
//

#include "i_limit.c"
#include "i_rateLimit.c"
#include "i_debug.c"
*/

int FlipperArm(int actDistance, int setDistance)
{
	int motorSpd;
	int rateError;
	rateError = (setDistance-actDistance)/6;
	motorSpd = LimitSym(rateError, 60);

	return motorSpd;
}
/*
#define FOREGROUND_MS 50
task Foreground(){
  int timeLeft,speedCmd;
  int flipperDistance = -600;
	nMotorEncoder[throwerMotor] = 0;
	//--------------------INIT Code---------------------------//

	//--------------------End INIT Code-----------------------//

	while(true){
		ClearTimer(T1);
		hogCPU();
		//--------------------Robot Code---------------------------//

		int moveDistClick = nMotorEncoder[throwerMotor];
		DebugInt("dist",moveDistClick);

    speedCmd = FlipperArm(moveDistClick, flipperDistance);

    DebugInt("spd",speedCmd);

		motor[throwerMotor]= speedCmd;

		//--------------------------End Robot Code--------------------------//
		// Wait for next itteration
	  timeLeft=FOREGROUND_MS-time1[T1];
	  releaseCPU();
	  wait1Msec(timeLeft);
	}// While
}//Foreground
task main()
{
	int iFrameCnt=0;
	DebugSkip(1);

  StartTask(Foreground, 255);

  while(true){

  	//-----------------Start i_debug.c output------------------//
  	if (debugRun==true){// Do not send out a stream if Debug is not called
			if (debugSkip<debugSkipI++){
	  		writeDebugStream("[%d] ",iFrameCnt);
	  		for (int i=0; i<debugI; ++i)
	  			writeDebugStream("%5s=%5d",debugStr[i],debugInt[i]);

	  		writeDebugStream("\n");
	  		debugSkipI=0;
			}
			iFrameCnt++;
			debugRun=false;
			debugI=0; //Clear the debug buffer
		}
		//------------------Stop i_debug.c output----------------------//

	}// While
}// Main
*/
