#pragma config(Motor,  motorB,          rightmotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftmotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[rightmotor]=0;
while (nMotorEncoder[rightmotor]<1800)
{
  motor[leftmotor]=92;

  motor[rightmotor]=100;
}
nMotorEncoder[rightmotor]=0;
while (nMotorEncoder[rightmotor]>-250)
{
  motor[leftmotor]=-100;

  motor[rightmotor]=-100;
}
motor[leftmotor]=0;
motor[rightmotor]=0;
wait1Msec(500);
nMotorEncoder[rightmotor]=0;
nMotorEncoder[leftmotor]=0;
while (nMotorEncoder[leftmotor]<810)
{
motor[leftmotor]=100;
}
nMotorEncoder[rightmotor]=0;
while (nMotorEncoder[rightmotor]<1550)
{
	motor[leftmotor]=98;
	motor[rightmotor]=100;
}
motor[leftmotor]=0;
motor[rightmotor]=0;
wait1Msec(500);

nMotorEncoder[leftmotor]=0;

while (nMotorEncoder[leftmotor]<350)
{
	motor[leftmotor]=100;
}
nMotorEncoder[rightmotor]=0
while (nMotorEncoder[rightmotor]<100)
{
	motor[leftmotor]=100;
	motor[rightmotor]=100;
}
}
