#pragma config(Motor,  motorA,          rightmotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftmotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
motor[rightmotor]=25;
motor[leftmotor]=25;
wait1Msec(5000);
motor[rightmotor]=0;
motor[leftmotor]=0;
}
