#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyro,           sensorNone)
#pragma config(Sensor, S3,     epod,           sensorSONAR)
#pragma config(Sensor, S4,     Color,          sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,          leftsweeper,   tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          light,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightmotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftmotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     blockgrabber,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     robotlifter,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     flagraiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     blockthrower,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "joystickShaper.c"

#include "i_limit.c"
#include "i_flipperArm_driver.c"
void initializeRobot()
{

}

//if
task main()
{
	initializeRobot();

  waitForStart();
	nMotorEncoder[robotlifter] = 0;
	nMotorEncoder[blockthrower] = 0;
	bool lifterTrigger = false;
	int lifterEncoder = 0;
	int lifterSpd = 0;
	string sColor;
	int throwerEncoder = 0;
	int throwerSpd = 0;
	int throwerSet = 0;
	int jstick2Y2 = 0;
	int jstick2Y1 = 0;
	while(true)
	{
		int jstickX = 0;
		int jstickY = 0;

		getJoystickSettings(joystick);
		jstick2Y1 = jsShape(joystick.joy2_y1);
		jstick2Y2 = -jsShape(joystick.joy2_y2);
		jstickX = jsShape(joystick.joy1_x2)*3/2;// makes driving less touchy... hopefully
		jstickY = jsShape(joystick.joy1_y2)*3/2;// same here

    motor[leftmotor] = (-jstickY + jstickX)/2; // uses revised values to make driving on one joystick
   	motor[rightmotor] = (-jstickY + -jstickX)/2;// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    motor[blockgrabber] = jstick2Y2;
		motor[leftsweeper] = -jstick2Y2;
		writeDebugStreamLine("Color=%d,light=%d",SensorValue[S4],motor[light]);
switch (SensorValue[S4])
{
case 0: sColor = "Black";motor[light]=0; break;
case 2: sColor = "Blue";motor[light]=0; break;
case 4: sColor = "Green";motor[light]=0; break;
case 6: sColor = "Yellow";motor[light]=100; break;
case 8: sColor = "Red";motor[light]=0; break;
case 17: sColor = "White";motor[light]=0; break;
default: sColor = "???";motor[light]=0; break;
}

// ********************* robotlifter ********************************
		lifterEncoder = nMotorEncoder[robotlifter];


		if (joy2Btn(2) && joy2Btn(6))
		{
			lifterTrigger = false;
			if (lifterEncoder >10)
				{
					lifterSpd = -40;

				}
			else
				{
					lifterSpd = 0;

				}
		}
		else if(joy2Btn(5) && joy2Btn(6))
  	{
  		lifterSpd = jstick2Y1;
  	}
		else if ((joy2Btn(4) && joy2Btn(6)) || lifterTrigger)
		{
			lifterTrigger = true;
			if (lifterEncoder < 11000)
				{
					lifterSpd = 40;
				}
			else
				{
					lifterSpd = 0;
					lifterTrigger = false;
				}
		}
  	else
  	{
  		lifterSpd = 0;
  	}

  	motor[robotlifter] = lifterSpd;
  	if(!(joy2Btn(5) && joy2Btn(6)))
		{
			motor[flagraiser] = jstick2Y1;
		}


//***************** block thrower **********************************************
			throwerEncoder = nMotorEncoder[blockthrower];
		writeDebugStreamLine("Encoder value = %d", throwerEncoder);
		writeDebugStreamLine("rspd = %d",motor[rightmotor] );
		writeDebugStreamLine("lspd = %d",motor[leftmotor] );// max power is 50
		writeDebugStreamLine("  %d",joystick.joy1_y2 );
				if (joy2Btn(8))
		{
			throwerSet = 2000;

		}

		else if (joy2Btn(7))
		{

			throwerSet = 10;

		}
 	else
  	{
  		throwerSet = throwerEncoder;
  	}

throwerSpd = FlipperArm(throwerEncoder, throwerSet);



//throwerSpd = jstick2Y2;

 motor[robotlifter] = lifterSpd;
 motor[blockthrower] = throwerSpd;

        wait1Msec(20);
  }
 motor[blockgrabber] = 0;
 motor[robotlifter] = 0;
 motor[rightmotor] = 0;
 motor[leftmotor] = 0;

}
