#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyro,           sensorNone)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          rightsweeper,  tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          leftsweeper,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightmotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftmotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     blockgrabber,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     robotlifter,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     flagraiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     blockthrower,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "joystickShaper.c"

#include "i_limit.c"
#include "i_flipperArm_driver.c"
#define LIGHT_OFF 0
#define LIGHT_ON_1 1
#define LIGHT_ON_2 2
#define FLASH 3
void initializeRobot()
{

}
task main()
{
	initializeRobot();

  waitForStart();
	nMotorEncoder[robotlifter] = 0;
	nMotorEncoder[blockthrower] = 0;
	bool lifterTrigger = false;
	int lifterEncoder = 0;
	int lifterSpd = 0;
int block_count = 0;
	int throwerEncoder = 0;
	int throwerSpd = 0;
	int throwerSet = 0;
	int jstick2Y2 = 0;
	int jstick2Y1 = 0;
	while(true)
	{
		int jstickX = 0;
		int jstickY = 0;

		getJoystickSettings(joystick);
		jstick2Y1 = jsShape(joystick.joy2_y1);
		jstick2Y2 = -jsShape(joystick.joy2_y2);
		jstickX = jsShape(joystick.joy1_x2)*3/2;// makes driving less touchy... hopefully
		jstickY = jsShape(joystick.joy1_y2)*3/2;// same here

    motor[leftmotor] = (-jstickY + jstickX)/2; // uses revised values to make driving on one joystick
   	motor[rightmotor] = (-jstickY + -jstickX)/2;// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    motor[blockgrabber] = jstick2Y2;
    motor[rightsweeper] = jstick2Y2;
		motor[leftsweeper] = -jstick2Y2;

		int sm_light=LIGHT_OFF;
switch (sm_light)
{

case LIGHT_OFF:

motor[light]=0;	//set light off

if(block_count==4)
{
sm_light=LIGHT_ON_2;
}

if(lifterEncoder==1900)
{
	block_count=0;
	sm_light=LIGHT_OFF;
}
	if (joystick.joy2_y2>0&SensorValue[S4]==7) // Block in and light sees yellow
	{
		++block_count;
		sm_light=LIGHT_ON_1;
	}
		if (joystick.joy2_y2<0&&SensorValue[S4]==7) // Block out and light sees yellow
	{
		--block_count;
		sm_light=LIGHT_ON_1;
}


case LIGHT_ON_1:

motor[light]=100;
if(lifterEncoder==1900)
{
	block_count=0;
	sm_light=LIGHT_OFF;
}
if (SensorValue[S4]==17)
{
sm_light=LIGHT_OFF;
}
if(joystick.joy2_y2>0&&SensorValue[S4]==17)
{
	--block_count;
	sm_light=LIGHT_OFF;
}
break;

case LIGHT_ON_2:

motor[light]=100;
if(block_count>4)
{
sm_light=FLASH;
}
if(lifterEncoder==1900)
{
	block_count=0;
	sm_light=LIGHT_OFF;
}

break;

case FLASH:

motor[light]=100;
wait1Msec(300);
motor[light]=0;
if(lifterEncoder==1900)
{
	block_count=0;
	sm_light=LIGHT_OFF;
}
if(joystick.joy2_y2>0&&SensorValue[S4]==17)
{
sm_light=LIGHT_ON_2;
}
break;
}


// ********************* robotlifter ********************************
		lifterEncoder = nMotorEncoder[robotlifter];


		if (joy2Btn(2) && joy2Btn(6))
		{
			lifterTrigger = false;
			if (lifterEncoder >10)
				{
					lifterSpd = -70;

				}
			else
				{
					lifterSpd = 0;

				}
		}
		else if(joy2Btn(5) && joy2Btn(6))
  	{
  		lifterSpd = jstick2Y1;
  	}
		else if ((joy2Btn(4) && joy2Btn(6)) || lifterTrigger)
		{
			lifterTrigger = true;
			if (lifterEncoder < 11000)
				{
					lifterSpd = 70;
				}
			else
				{
					lifterSpd = 0;
					lifterTrigger = false;
				}
		}
  	else
  	{
  		lifterSpd = 0;
  	}

  	motor[robotlifter] = lifterSpd;
  	if(!(joy2Btn(5) && joy2Btn(6)))
		{
			motor[flagraiser] = jstick2Y1;
		}


//***************** block thrower **********************************************
			throwerEncoder = nMotorEncoder[blockthrower];
		writeDebugStreamLine("Encoder value = %d", throwerEncoder);
		writeDebugStreamLine("rspd = %d",motor[rightmotor] );
		writeDebugStreamLine("lspd = %d",motor[leftmotor] );// max power is 50
		writeDebugStreamLine("  %d",jstick2Y1 );
				if (joy2Btn(8))
		{
			throwerSet = 2000;

		}

		else if (joy2Btn(7))
		{

			throwerSet = 10;

		}
 	else
  	{
  		throwerSet = throwerEncoder;
  	}

throwerSpd = FlipperArm(throwerEncoder, throwerSet);



//throwerSpd = jstick2Y2;

 motor[robotlifter] = lifterSpd;
 motor[blockthrower] = throwerSpd;

        wait1Msec(20);
  }
 motor[blockgrabber] = 0;
 motor[robotlifter] = 0;
 motor[rightmotor] = 0;
 motor[leftmotor] = 0;

}
