/*#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorNone)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          rightsweeper,  tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          leftsweeper,   tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     ltWheelMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rtWheelMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     blockgrabber,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!
//====================Add / for debug======================//
#include "i_debug.c"
#include "i_rateLimit.c"
#include "i_limit.c"*/
//
// Story: As a software designer I want to control the direction the robot goes.
// Assume that the left motor is called motorLt and the right motor is
// Dependency: i_rateLimit.c, i_limit.c
// Usage: A positive dirCmd is turn right. Returns the direction command.
// Tuning:
#define DEG2CLK 29
#define DIR_KP 20 // Start tuning by setting this to around 25. Bigger numbers are a smaller gain
#define DIR_RL 100
//------------------Direction Controller-----------------------//
//int robotDirInt=nMotorEncoder[ltWheelMotor] - nMotorEncoder[rtWheelMotor];
//dirCmdInt=Direction(dirCmdInt, robotDirInt);
int directionRl=0;
long Direction(long dirCmd, long dir)
{
	int dirMotorCmd;

	dirCmd=RateLimit(dirCmd*DEG2CLK,DIR_RL,directionRl);
	dirMotorCmd = (dirCmd-dir)/DIR_KP;

	return(dirMotorCmd);
}
//------------------Direction Reset-----------------------//
void DirectionReset(){
	directionRl=0;
}
//====================Add / for debug======================//
// Add this code to a while loop in main
// Unit Test
// [] drive forward to specific inch distance
// [] drive backward to a specific inch distance

/*#define FOREGROUND_MS 50
task Foreground(){
  int timeLeft;
//	int iFrameCnt=0;
//	int out,in=0;


	while(true){
		ClearTimer(T1);
		hogCPU();
		//--------------------UNIT TEST Code---------------------------//

		int rDirCmd=-90; // Degrees

  	DebugInt("rDir",rDirCmd);

		int robotDir=nMotorEncoder[ltWheelMotor] - nMotorEncoder[rtWheelMotor];
		int dirCmd=Direction(rDirCmd, robotDir);
//  	DebugInt("ltEnc",nMotorEncoder[ltWheelMotor]);
//  	DebugInt("rtEnc",nMotorEncoder[rtWheelMotor]);

  	DebugInt(" rdir",robotDir);
		motor[ltWheelMotor]=dirCmd;
		motor[rtWheelMotor]=-dirCmd;

		//--------------------------End UNIT TEST Code--------------------------//
		// Wait for next itteration
	  timeLeft=FOREGROUND_MS-time1[T1];
	  releaseCPU();
	  wait1Msec(timeLeft);
	}// While
}//Foreground
task main()
{
	int iFrameCnt=0;
	//--------------------UNIT TEST INIT Code---------------------------//

		nMotorEncoder[ltWheelMotor]=0;
		nMotorEncoder[rtWheelMotor]=0;
	int	inDelta=0;
	int	inOld=0;
	int	cKi=0;

	//--------------------------End UNIT TEST INIT Code--------------------------//

  StartTask(Foreground, 255);

  while(true){

  	//-----------------Start i_debug.c output------------------//
  	if (debugRun==true){// Do not send out a stream if Debug is not called
			if (debugSkip<debugSkipI++){
	  		writeDebugStream("[%d] ",iFrameCnt);
	  		for (int i=0; i<debugI; ++i)
	  			writeDebugStream("%5s=%5d",debugStr[i],debugInt[i]);

	  		writeDebugStream("\n");
	  		debugSkipI=0;
			}
			iFrameCnt++;
			debugRun=false;
			debugI=0; //Clear the debug buffer
		}
		//------------------Stop i_debug.c output----------------------//

	}// While
}// Main
//*/
