#pragma config(Sensor, S2,     ,               sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
	writeDebugStreamLine("ir=%d",SensorValue[S2] );
	}

}
