#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  motorA,          leftsweeper,   tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          light,         tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     ltMotor,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rtMotor,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     ltBack,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rtBack,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     flagraiser,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     blockthrower,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     robotlifter,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     blockgrabber,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    irArm,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "i_PID2.c"
#include "i_delayatrue.c"
#include "i_debug.c"
#include "i_limit.c"
#include "i_rateLimit.c"
#include "i_direction.c"-------------------------------------------------------------------------------------------------------------------------------
#include "i_forwardDist.c"
#include "i_flipperArm_auto.c"
//-------------------Path definition----------------------//
// dist, dir, spd
int path[][]={
		{20, 0, 50},
		{28, -47, 50},
		{88, -47, 50},
		{70, -47, 50},
								};
int armSetPos = 0;
#define SPD 40;
#define DIST_IDX 0
#define DIR_IDX 1
#define SPD_IDX 2
int pathIdx=0;
int speedCmdZ1=0;
int countState = 0;
int rightmotors;
int leftmotors;
void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}



//*--------------------Foreground---------------------------//
// Story: As a player, I want the robot to follow a path so i can score autonomous points in a game
// [x] Follow path stored in an array
// [x] Stop at the end of the path
#define FOREGROUND_MS 50
task Foreground(){
	//servoChangeRate[servo2] = 2;
  int timeLeft;
int state=0;
	Pid_Init();
	Pid_Init2();
	servo[irArm]=243;
	while(true){
		ClearTimer(T1);
		hogCPU();
		//--------------------Robot Code---------------------------//
	long armEncoder = nMotorEncoder[blockthrower];
	long  robotDist = nMotorEncoder[rtMotor] + nMotorEncoder[ltMotor];
	long  robotDir  = nMotorEncoder[ltMotor] - nMotorEncoder[rtMotor];
	long  distInches = robotDist/IN2CLK;
	long  dirDegrees = robotDir/27;
		// Calculate the speed and direction commands
    int speedCmd = ForwardDist(path[pathIdx][DIST_IDX], robotDist, path[pathIdx][SPD_IDX]);
		int dirCmd=Direction(path[pathIdx][DIR_IDX], robotDir);
		int armSpd = FlipperArm(armEncoder, armSetPos);
	bool IRval;
	//calculate when to increment path
if (abs(path[pathIdx][DIR_IDX] - dirDegrees) < 4 && abs(path[pathIdx][DIST_IDX] - distInches) < 3) pathIdx++;
// State O Follow Path

if (state==0)
{
	if (distInches>28&&distInches<48)
	{
		state=1;
	}
}
if(state==1)
{
	servo[irArm]=95;
	if (distInches>48)
	{

		state=2;
	}
}
IRval = Delayatrue(1, SensorValue[IR] == 1 || SensorValue[IR] == 2);
// State 1 Look for IR Beacon
 if (state==2)
 {
   speedCmd=10;
  if ( IRval)
  {
  	state=7;
  }
  else
  {
  	state=3;
  }
}
// State 2 Follow Path
if (state==3)
{

	if (distInches>55)
	{
		state=4;
	}

}
// State 3 Look for IR Beacon
 if (state==4)
 {
   speedCmd=10;
  if ( IRval==true)
  {
  	state=8;
  }
  else
  {
  	state=5;
  }
  servo[irArm]=243;
}
// State 4 Follow Path
if (state==5)
{
	if (distInches>74)//36
	{
		state=6;
	}

}

// State 5 Look for IR Beacon
 if (state==6)
 {
   speedCmd=10;
  if ( IRval==true)
  {
  	state=8;
  }
  else
  {
  	state=7;
  }
}
// State 6 Follow Path
if (state==7)
{
	if (pathIdx == 3)//45
	{
		state=8;
	}
}

if (state==8)// flip arm
{
	speedCmd=0;
	dirCmd = 0;
	armSetPos = 2300;
		if (abs(armSetPos - armEncoder) <10)
		{
			countState++;

			state=9;
		}

}
if (state==9)
{
	speedCmd = 0;
	dirCmd = 0;
	armSetPos = 0;
		if (abs(armSetPos - armEncoder) < 400)
		{
			pathIdx=3;
			state=10;
		}
}
if (state==10)
{
servo[irArm]=243;
state=11;
}
if(state==11)
{
}

		DebugInt("spd",speedCmd);
		DebugInt("dir",robotDir/DEG2CLK);
		DebugInt("dist",distInches);
//		DebugInt("path",pathIdx);
    DebugInt("state",state);
    DebugInt("irval",SensorValue[IR]);


		// Calculate when to move to the next path index

		int s=sizeof(path)/sizeof(path[0])-1;
		DebugInt("siz",s);
		if (pathIdx>s) pathIdx=s;
		speedCmd = RateLimit(speedCmd, START_RATE,speedCmdZ1 );
		rightmotors=Pid(speedCmd-dirCmd, nMotorEncoder[rtMotor]);
		leftmotors=Pid2(speedCmd+dirCmd, nMotorEncoder[ltMotor]);
		motor[rtBack]=rightmotors;
		motor[rtMotor]=rightmotors;
		motor[ltMotor]=leftmotors;
		motor[ltBack]=leftmotors;
		motor[blockthrower]=armSpd;
		DebugInt("rightmotors",rightmotors);
		DebugInt("leftmotors",leftmotors);

		//--------------------------Robot Code--------------------------//
		// Wait for next itteration
	  timeLeft=FOREGROUND_MS-time1[T1];
	  releaseCPU();
	  wait1Msec(timeLeft);
	}// While
}//Foreground
task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.


	int iFrameCnt=0;

	//--------------------INIT Code---------------------------//
  ForwardDistReset((tMotor)rtMotor, (tMotor)ltMotor);
	DirectionReset();
	nMotorEncoder[blockthrower] = 0;
	speedCmdZ1=0;
	pathIdx=0;
	delayatruecount=0;


	//--------------------End INIT Code--------------------------//

  StartTask(Foreground, 255);

  while(true){

  	//-----------------Start i_debug.c output------------------//
  	if (debugRun==true){// Do not send out a stream if Debug is not called
			if (debugSkip<debugSkipI++){
	  		writeDebugStream("[%d] ",iFrameCnt);
	  		for (int i=0; i<debugI; ++i)
	  			writeDebugStream(" %5s=%5d",debugStr[i],debugInt[i]);

	  		writeDebugStream("\n");
	  		debugSkipI=0;
			}
			iFrameCnt++;
			debugRun=false;
			debugI=0; //Clear the debug buffer
		}
		//------------------Stop i_debug.c output----------------------//

	}// While
}// Main
