#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rtMotor,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rtBack,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     ltMotor,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     ltBack,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     blockthrower,  tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "i_PID2.c"

#include "i_delayatrue.c"
#include "i_debug.c"
#include "i_limit.c"
#include "i_rateLimit.c"
#include "i_direction.c"-------------------------------------------------------------------------------------------------------------------------------
#include "i_forwardDist.c"
#include "i_flipperArm_auto.c"
int rightmotors;
int leftmotors;

//-------------------Path definition----------------------//
// dist, dir, spd
int path[][]={\
		{20, 0, 50},
		{28, -47, 50},
		{88, -47, 40},
		{53, -47, 50},
								};
int armSetPos = 0;
#define SPD 40;
#define DIST_IDX 0
#define DIR_IDX 1
#define SPD_IDX 2
int pathIdx=0;
int speedCmdZ1=0;
int countState = 0;
void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}



//*--------------------Foreground---------------------------//
// Story: As a player, I want the robot to follow a path so i can score autonomous points in a game
// [x] Follow path stored in an array
// [x] Stop at the end of the path
#define FOREGROUND_MS 50
task Foreground(){
	Pid_Init();
	Pid_Init2();

  int timeLeft;
int state=0;
	while(true){
		ClearTimer(T1);
		hogCPU();
		//--------------------Robot Code---------------------------//
	long armEncoder = nMotorEncoder[blockthrower];
	long  robotDist = nMotorEncoder[rtMotor] + nMotorEncoder[ltMotor];
	long  robotDir  = nMotorEncoder[ltMotor] - nMotorEncoder[rtMotor];
	long  distInches = robotDist/IN2CLK;
	long  dirDegrees = robotDir/27;
		// Calculate the speed and direction commands
    int speedCmd = ForwardDist(path[pathIdx][DIST_IDX], robotDist, path[pathIdx][SPD_IDX]);
		int dirCmd=Direction(path[pathIdx][DIR_IDX], robotDir);
		int armSpd = FlipperArm(armEncoder, armSetPos);
	bool IRval;
	//calculate when to increment path
if (abs(path[pathIdx][DIR_IDX] - dirDegrees) < 4 && abs(path[pathIdx][DIST_IDX] - distInches) < 3) pathIdx++;
// State O Follow Path
if (state==0)
{
	if (distInches>48)
	{
		state=1;
	}
}
IRval = Delayatrue(1, SensorValue[IR] == 1 || SensorValue[IR] == 2);
// State 1 Look for IR Beacon
 if (state==1)
 {
   speedCmd=10;
  if ( IRval)
  {
  	state=7;
  }
  else
  {
  	state=2;
  }
}
// State 2 Follow Path
if (state==2)
{

	if (distInches>55)
	{
		state=3;
	}

}
// State 3 Look for IR Beacon
 if (state==3)
 {
   speedCmd=10;
  if ( IRval==true)
  {
  	state=7;
  }
  else
  {
  	state=4;
  }
}
// State 4 Follow Path
if (state==4)
{
	if (distInches>74)//36
	{
		state=5;
	}

}

// State 5 Look for IR Beacon
 if (state==5)
 {
   speedCmd=10;
  if ( IRval==true)
  {
  	state=7;
  }
  else
  {
  	state=6;
  }
}
// State 6 Follow Path
if (state==6)
{
	if (pathIdx == 3)//45
	{
		state=7;
	}
}

if (state==7)// flip arm
{
	speedCmd=0;
	dirCmd = 0;
	armSetPos = 2300;
		if (abs(armSetPos - armEncoder) <10)
		{
			countState++;

			state=8;
		}

}
if (state==8)
{
	speedCmd = 0;
	dirCmd = 0;
	armSetPos = 0;
		if (abs(armSetPos - armEncoder) < 400)
		{
			pathIdx=3;
			state=9;
		}
}
if (state==9)
{

}

		DebugInt("spd",speedCmd);
		DebugInt("dir",robotDir/DEG2CLK);
		DebugInt("dist",distInches);
		DebugInt("path",pathIdx);
    DebugInt("state",state);
    DebugInt("irval",SensorValue[IR]);


		// Calculate when to move to the next path index

		int s=sizeof(path)/sizeof(path[0])-1;
		DebugInt("siz",s);
		if (pathIdx>s) pathIdx=s;
	speedCmd = RateLimit(speedCmd, START_RATE,speedCmdZ1 );
		rightmotors=Pid(speedCmd-dirCmd, nMotorEncoder[rtMotor]);
		leftmotors=Pid2(speedCmd+dirCmd, nMotorEncoder[ltMotor]);
		motor[rtBack]=rightmotors;
		motor[rtMotor]=rightmotors;
		motor[ltMotor]=leftmotors;
		motor[ltBack]=leftmotors;
		motor[blockthrower]=armSpd;
		DebugInt("rightmotors",rightmotors);
		DebugInt("leftmotors",leftmotors);
		//--------------------------Robot Code--------------------------//
		// Wait for next itteration
	  timeLeft=FOREGROUND_MS-time1[T1];
	  releaseCPU();
	  wait1Msec(timeLeft);
	}// While
}//Foreground
task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.


	int iFrameCnt=0;

	//--------------------INIT Code---------------------------//
  ForwardDistReset((tMotor)rtWheelMotor, (tMotor)ltWheelMotor);
	DirectionReset();
	nMotorEncoder[blockthrower] = 0;
	speedCmdZ1=0;
	pathIdx=0;
	delayatruecount=0;


	//--------------------End INIT Code--------------------------//

  StartTask(Foreground, 255);

  while(true){

  	//-----------------Start i_debug.c output------------------//
  	if (debugRun==true){// Do not send out a stream if Debug is not called
			if (debugSkip<debugSkipI++){
	  		writeDebugStream("[%d] ",iFrameCnt);
	  		for (int i=0; i<debugI; ++i)
	  			writeDebugStream(" %5s=%5d",debugStr[i],debugInt[i]);

	  		writeDebugStream("\n");
	  		debugSkipI=0;
			}
			iFrameCnt++;
			debugRun=false;
			debugI=0; //Clear the debug buffer
		}
		//------------------Stop i_debug.c output----------------------//

	}// While
}// Main
