#pragma config(Sensor, S1,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     Color,          sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          action,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
string sColor;

while (true) {
switch (SensorValue[S4])
{
case 0: sColor = "Black"; break;
case 2: sColor = "Blue"; break;
case 4: sColor = "Green"; break;
case 6: sColor = "Yellow"; break;
case 8: sColor = "Red"; break;
case 17: sColor = "White"; break;
default: sColor = "???"; break;
}
nxtDisplayCenteredTextLine(2, sColor);
wait1Msec(50);
}
}
