#pragma config(Motor,  motorA,          rightmotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftmotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightmotor]=-100;
motor[leftmotor]=100;
wait1Msec(3000);
motor[rightmotor]=0;
motor[leftmotor]=0;
}
