#pragma config(Motor,  motorA,          rightmotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftmotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "i.backward.c"
#include "i.forward.c"
#include "i.right.c"
#include "i.left.c"



task main()
{

Forward(50,5);

}
