#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          leftmotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightmotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{

while(true)
{
motor[leftmotor]=(joystick.joy1_y2)/2;
motor[rightmotor]=(joystick.joy1_y2)/2;
}

}
