#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "i_forward.c"
#include "i_turn.c"

#define FORWARD 0
#define READ_IR 1
#define DRIVE_POSITION1 2
#define DRIVE_POSITION2 3
#define DRIVE_POSITION3 4
#define STOP 5
#define IR_0 6

int sm = FORWARD;
bool forward_true;
bool turn_true;


task main()
{
forward_intizalize();
	while(true)
	{

		writeDebugStreamLine("sm=%d, encoder=%d, ir=%d",sm,nMotorEncoder[ltWheelMotor],SensorValue[IR]);

		switch(sm)
		{
		case FORWARD:
		 forward_true=forward2(25,3500);
		  if(forward_true==true)
		  {
		  sm=READ_IR;
			}
		break;

	case READ_IR:

	if(SensorValue[IR]==4)
		{
		sm=DRIVE_POSITION1;
		}

	if(SensorValue[IR]==5)
		{
		sm=DRIVE_POSITION2;
		}

	if(SensorValue[IR]==6)
		{
		sm=DRIVE_POSITION3;
		}

			if(SensorValue[IR]==0)
		{
		sm=IR_0;
		}

	break;

	case DRIVE_POSITION1:
		turn_true=Turnleft(25,90);
		if(turn_true==true)
		{
		sm=STOP;
		}
		break;

	case DRIVE_POSITION2:
		turn_true=Turnright(25,90);
		if(turn_true==true)
		{
		sm=STOP;
		}
		break;

	case DRIVE_POSITION3:
		turn_true=Turnleft(25,180);
		if(turn_true==true)
		{
		sm=STOP;
		}
		break;

		case STOP:
		motor[rtWheelMotor]=0;
		motor[ltWheelMotor]=0;
		break;

		case IR_0:
		forward_true=forward(-25,-3500);
		break;
		}
		wait1Msec(100);
	}
}
