#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// As a driver I use the right joystick to drive
//  Feature: Lookup is a table lookup routine that can shape the output joystick
//  To use, remove the comments.


#include "JoystickDriver.c"
#include "i_lookup.c"
#include "i_deadZone.c"

#pragma DebuggerWindows("joystickSimple");

int jstickX;
int jstickY;
int gyroBias=0;

void initializeRobot()
{
	servo(dump)=195;
	servo(clamp)=70;

	for (int i=0; i<5; i++){
		gyroBias = SensorValue[gyro]+gyroBias;
		wait1Msec(50);
	}
	gyroBias=gyroBias/5;


	return;
}

task main()
{
	initializeRobot();

	while(true)
	{
  	getJoystickSettings(joystick);


		jstickY = Lookup1(joystick.joy1_y2);
		jstickX = Lookup1(joystick.joy1_x2) - DeadZone((SensorValue[gyro]-gyroBias)/2,5); // Gyro


		// ------- Control the drive motors ----------//
		motor[ltWheelMotor]=(jstickY + jstickX);
		motor[rtWheelMotor]=(jstickY - jstickX);



writeDebugStreamLine("%d,%d",nMotorEncoder[rtWheelMotor],nMotorEncoder[ltWheelMotor]);
		wait1Msec(50);

		/*if (joy1Btn(1))
		{
			servo[hook]=20;
		}

		else
		{
			servo[hook]=160;
		}*/
	}
}
