#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// As a driver I use the right joystick to drive
//  Feature: Lookup is a table lookup routine that can shape the output joystick
//  To use, remove the comments.
//
#include "JoystickDriver.c"
#include "i_clamp.c"
#include "i_dump.c"
#include "i_arm.c"
#pragma DebuggerWindows("JoystickGame")
//#include "i_lookup.c"

int jstickX;
int jstickY;
int gyroBias=0;

void initializeRobot()
{
	servo(dump)=195;
	servo(clamp)=70;

//	for (int i=0; i<5; i++){
//		gyroBias = SensorValue[gyroSensor]+gyroBias;
//		wait1Msec(50);
//	}
//	gyroBias=gyroBias/5;


	return;
}
task main()
{
	initializeRobot();
	waitForStart();

	while(true)
	{
		getJoystickSettings(joystick);

		/////////Joystick 1//////////

		//jstickX = Lookup1(joystick.joy1_x2); // No gyro
		//jstickX = Lookup1(joystick.joy1_x2) - DeadZone((SensorValue[gyroSensor]-gyroBias)/2,5); // Gyro
		//jstickY = Lookup1(joystick.joy1_y2);

		// ------- Control the drive motors ----------//
		//motor[ltMotor]=(jstickY + jstickX);
		//motor[rtMotor]=(jstickY - jstickX);

		motor[rtWheelMotor]=(joystick.joy1_y2-joystick.joy1_x2)/2;
		motor[ltWheelMotor]=(joystick.joy1_y2+joystick.joy1_x2)/2;

		////////Joystick 2//////////

		motor[sweeper]=joystick.joy2_y2;


		if(joy2Btn(3))
		{
			motor[lift]=joystick.joy2_y1;
		}

		if(joy2Btn(1))//Position 0: Bottom position
		{
			RaiseArm(-25,120);
		}

		if(joy2Btn(2))//Position 1: Smallest rolling goal
		{
			RaiseArm(25,7900);
		}

		writeDebugStreamLine("%d", nMotorEncoder[lift]);

		if(joy2Btn(7))
		{
			Clampgoal(true);
		}
		else
		{
			Clampgoal(false);
		}

		if(joy2Btn(8))
		{
			DumpBucket(true);
		}
		else
		{
			DumpBucket(false);
		}

		wait1Msec(50);
	}
}
