#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
servo[clamp]=0;
servo[dump]=-0;
	while(true)
	{
		getJoystickSettings(joystick);

		/////////Joystick 1//////////

		motor[rtWheelMotor]=(joystick.joy1_y2+joystick.joy1_x2)/2;
		motor[ltWheelMotor]=(joystick.joy1_y2-joystick.joy1_x2)/2;

		////////Joystick 2//////////

		motor[sweeper]=joystick.joy2_y2;


		motor[lift]=joystick.joy2_y1;

		if(joy2Btn(7))
		{
			servo[clamp]=120;
		}

			if(joy2Btn(5))
			{
				servo[clamp]=0;
			}

				if(joy2Btn(8))
				{
					servo[dump]=0;
				}

					if(joy2Btn(6))
					{
						servo[dump]=-100;
					}

	}
}
