#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



#define FORWARD 0
#define AUTO_SCORE 1
#define GRAB 2
#define TURN 3
#define BACKWARD 4
#define STOP 5

int sm = FORWARD;

int InitializeValue;
int TargetValue;
#define ENCODER_SET
#define MOVE

int sm2 = ENCODER_SET;

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "i_forward.c"
#include "i_score.c"
#include "i_clamp.c"
#include "i_turn.c"

void initializeRobot()
{
servo(dump)=100;
servo(clamp)=0;
servo[score]=120;

forward_initizalize();


  return;
}

#pragma DebuggerWindows("JoystickGame")

task main()
{

  initializeRobot();

  waitForStart();

  while(true)
  {
    switch(sm)
		{
		case FORWARD:

		writeDebugStreamLine("right=%d", nMotorEncoder[rtWheelMotor]);
		writeDebugStreamLine("left=%d", nMotorEncoder[ltWheelMotor]);

		  forward(20,8500);



		  if( forward(20,1950)==true)
		  {
		  sm=AUTO_SCORE;
			}

		break;


  	case AUTO_SCORE:

  	Auto_Score();
  	if(Auto_Score())
		{
			sm=GRAB;
		}

		break;

		case GRAB:

			servo[clamp]=70;

			wait1Msec(1000);

			sm=TURN;


		break;

		case TURN:

			Turnleft(25,25);

			if(Turnleft(25,25)==true)
			{
			sm=BACKWARD;
			}

		break;

		case BACKWARD:
		backward(25,6250);

		if(backward(25,6250)==true)
		{
		sm=STOP;
		}

		break;

		case STOP:

		motor[rtWheelMotor]=0;
		motor[ltWheelMotor]=0;
		servo[clamp]=140;

		break;
  	}
	}
}
