#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



#define FORWARD 0
#define AUTO_SCORE 1
#define GRAB 2
#define TURN 3
#define BACKWARD 4
#define STOP 5


int sm = FORWARD;
int forward_true;

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "i_forward.c"
#include "i_score.c"
#include "i_clamp.c"
#include "i_turn.c"

void initializeRobot()
{
servo(dump)=195;
servo(clamp)=0;
servo[score]=120;

forward_initialize();

  return;
}

#pragma DebuggerWindows("JoystickGame")

task main()
{
  initializeRobot();

  waitForStart();

  while(true)
  {
  		switch(sm)
		{
		case FORWARD:

		 forward_true=forward(50,8500);

		  sm=AUTO_SCORE;

		break;


  	case AUTO_SCORE:

  	Auto_Score();
  	if(Auto_Score())
		{
			sm=GRAB;
			count=0;
		}

		break;

		case GRAB:

			servo[clamp]=70;

			count+=1;

			if(count>21)
			{
			sm=TURN;
			count=0;
			}

		break;

		case TURN:

			Turnleft(10,5);

			if(Turnleft(25,40)==true)
			{
			sm=BACKWARD;
			}

		break;

		case BACKWARD:
		backward(25,16000);

		if(backward(25,16000)==true)
		{
		sm=STOP;
		}

		break;

		case STOP:

		motor[rtWheelMotor]=0;
		motor[ltWheelMotor]=0;
		servo[clamp]=100;

		break;
  	}
	}
}
