#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void LiftArm0(bool liftarm0) //position 0 is the position to collect balls
{
	if(liftarm0)
		{
			if(nMotorEncoder[lift]<0)
			{
				motor[lift]=50;
			}
	}
		else
		{
		motor[lift]=0;
		}
	return;
}

void LiftArm1(bool liftarm1) //position 1 is the position to score in small goal
{
	if(liftarm1)
		{
			if(nMotorEncoder[lift]<0)
			{
				motor[lift]=50;
			}
	}
		else
		{
		motor[lift]=0;
		}
	return;
}

void LiftArm2(bool liftarm2) //position 2 is the position to score in medium goal
{
	if(liftarm2)
		{
			if(nMotorEncoder[lift]<0)
			{
				motor[lift]=50;
			}
	}
		else
		{
		motor[lift]=0;
		}
	return;
}

void LiftArm3(bool liftarm3) //position 3 is the position to score in large goal
{
	if(liftarm3)
		{
			if(nMotorEncoder[lift]<0)
			{
				motor[lift]=50;
			}
	}
		else
		{
		motor[lift]=0;
		}
	return;
}

void LiftArm4(bool liftarm4) //position 4 is the position to score in center goal
{
	if(liftarm4)
		{
			if(nMotorEncoder[lift]<0)
			{
				motor[lift]=50;
			}
	}
		else
		{
		motor[lift]=0;
		}
	return;
}

task main()
{

}
