#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void IrReading(int ir_position)
	{
		bool Infared;
		while(true)
		{
		writeDebugStreamLine("%d",SensorValue[IR]);

			if(SensorValue[IR]==ir_position)
			{
			Infared=true;
			}

			else
			{
			Infared=false;
			}
		}

		return;
	}
