#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(true)
{
nxtDisplayBigTextLine(5, "%d",SensorValue[IR]);

wait1Msec(50);
}
}
