#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    score,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    ir,                   tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FORWARD 0
#define IR 1
#define POSITION_1 2
#define POSITION_2 3
#define POSITION_3 4

int sm = FORWARD;

#define ENCODER_SET 0
#define MOVE 1

int sm2 = ENCODER_SET;

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "i_forward.c"
#include "i_score.c"
#include "i_clamp.c"
#include "i_turn.c"

void initializeRobot()
{
servo(dump)=100;
servo(clamp)=0;
servo[score]=230;

forward_initizalize();


  return;
}

task main()
{

  initializeRobot();

  waitForStart();

  while(true)
  {
    switch(sm)
		{

		case FORWARD:
		writeDebugStreamLine("%d",SensorValue[IR]);
		if (forward(50,4000)==true)
		{
		wait1Msec(1000);
		writeDebugStreamLine("%d",SensorValue[IR]);
		sm=IR;
		}

		break;

		case IR:

		writeDebugStreamLine("%d",SensorValue[IR]);

		if (SensorValue[IR]==3)
		{
		sm=POSITION_1;
		}

		if (SensorValue[IR]==5||SensorValue[IR]==4)
		{
		sm=POSITION_2;
		}

		if (SensorValue[IR]==7||SensorValue[IR]==6)
		{
		sm=POSITION_3;
		}

		break;

		case POSITION_1:

		Turnright(25,90);

		break;

		case POSITION_2:

		Turnleft(25,180);

		break;

		case POSITION_3:

		backward(25,1000);

		break;


		}
	}
}
