#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     rtWheelMotor,  tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ltWheelMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     sweeper,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    clamp,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    ir,                   tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "i_forward.c"
#include "i_turn.c"

#define FORWARD 0
#define TURN 1
#define RAISE_ARM 2
#define DUMP_BUCKET 3
#define LOWER_ARM 4


int sm = FORWARD;


task main()
{
	while(true)
	{

		writeDebugStreamLine("sm=%d, encoder=%d, ir=%d,servo=%d",sm,nMotorEncoder[ltWheelMotor],SensorValue[IR],servo[ir]);

		switch(sm)
		{
		case FORWARD:
		 forward_true=forward2(-50,-7600);

		  if(forward_true==true)
		  {
		  sm=MOVE_SERVO;
			}
		break;

	case READ_IR:

	if(servo[ir]==172)//156
		{
		sm=DRIVE_POSITION1;
		}

	if(servo[ir]==228)//228
		{
		sm=DRIVE_POSITION2;
		}

	if(servo[ir]==252)//244
		{
		sm=DRIVE_POSITION3;
		}

		/*	if(SensorValue[IR]==0)
		{
		//sm=IR_0;
		}*/

	break;

	case DRIVE_POSITION1:
		turn_true=Turnleft(25,90);
		if(turn_true==true)
		{
		sm=STOP;
		}
		break;

	case DRIVE_POSITION2:
		turn_true=Turnright(25,90);
		if(turn_true==true)
		{
		sm=STOP;
		}
		break;

	case DRIVE_POSITION3:
		turn_true=Turnleft(25,180);
		if(turn_true==true)
		{
		sm=STOP;
		}
		break;

		case STOP:
		motor[rtWheelMotor]=0;
		motor[ltWheelMotor]=0;
		break;

}
